"""Adiciona tabelas de projeto e colunas project_id nulas.

Revision ID: 8d57e5ea91ec
Revises: 
Create Date: 2025-07-07 01:20:54.320373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d57e5ea91ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counter')
    with op.batch_alter_table('saved_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('saved_character_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('saved_scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('saved_scenario_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('saved_scenario_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('project_id')

    with op.batch_alter_table('saved_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('saved_character_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('project_id')

    op.create_table('counter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('counter_pkey'))
    )
    # ### end Alembic commands ###
